const KEY='gestoria-v1';const now=new Date();const $=id=>document.getElementById(id);const money=n=>(Number(n)||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'});const nid=()=>crypto.randomUUID();
function load(){const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):{entidades:[{id:'e1',nif:'',nombre:'Mi actividad'}],docs:[],pagos:{}};}function save(s){const c=structuredClone(s);c.docs.forEach(d=>{if(d.archivo&&d.archivo.length>900000)d.archivo=null;});localStorage.setItem(KEY,JSON.stringify(c));}
let state=load(),archivoActual=null,archivoNombre='',editId=null;
if(window.pdfjsLib){pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';}
function es3T(f){if(!f)return false;const[y,m]=f.split('-').map(Number);return y===2026&&m>=7&&m<=9;}
function clock(){const d=new Date('2026-10-15T23:59:59'),p=new Date('2026-10-20T23:59:59');const via=now<=d?'Aun cabe domiciliar (hasta el 15 de octubre).':now<=p?'Ya no cabe domiciliar. Paga y guarda el NRC (hasta el 20 de octubre).':'Fuera de plazo voluntario del 3T.';$('clock').innerHTML='<b>3T 2026 · IVA</b><p>Domiciliacion: 15 oct · Presentacion: 20 oct.<br>'+via+'</p>';if($('viaPago'))$('viaPago').textContent=via;}
function fillEnt(sel){if(!sel)return;sel.innerHTML=state.entidades.map(e=>'<option value="'+e.id+'">'+(e.nombre||'Sin nombre')+(e.nif?' · '+e.nif:'')+'</option>').join('');}
function renderEnt(){fillEnt($('entidad'));fillEnt($('entidad303'));$('listaEnt').innerHTML=state.entidades.map(e=>'<div class="item"><div><b>'+e.nombre+'</b><br><small>'+(e.nif||'Sin NIF')+'</small></div><button class="btn ghost" data-del-ent="'+e.id+'">Quitar</button></div>').join('')||'<p class="muted">Anade una entidad.</p>';}
function cuadran(d){const b=+d.base||0,c=+d.cuota||0,t=+d.total||0;if(!t&&!b)return false;return Math.abs(b+c-t)<0.05;}
function duplicado(doc,ignoreId){if(!doc.nif||!doc.numero)return false;return state.docs.some(d=>d.id!==ignoreId&&d.estado!=='rechazado'&&d.nif.replace(/\s/g,'').toUpperCase()===doc.nif.replace(/\s/g,'').toUpperCase()&&d.numero.trim().toUpperCase()===doc.numero.trim().toUpperCase());}
function renderLista(){const orden=[...state.docs].sort((a,b)=>(b.fecha||'').localeCompare(a.fecha||''));$('lista').innerHTML=orden.map(d=>{const ent=state.entidades.find(e=>e.id===d.entidadId);return '<div class="item"><div><span class="st '+d.estado+'">'+d.estado+'</span><b> '+(d.nombre||d.nif||'Sin nombre')+'</b><br><small>'+(ent?ent.nombre:'')+' · '+d.tipo+' · '+(d.fecha||'sin fecha')+' · '+(d.numero||'s/n')+' · '+money(d.total)+'</small></div><div><button class="btn ghost" data-edit="'+d.id+'">Abrir</button>'+(d.estado!=='validado'?'<button class="btn ok" data-val="'+d.id+'">Validar</button>':'')+(d.estado!=='rechazado'?'<button class="btn ghost" data-rej="'+d.id+'">Rechazar</button>':'')+'</div></div>';}).join('')||'<p class="muted">Aun no hay documentos.</p>';}
function resumen303(id){const pendientes=state.docs.filter(d=>d.entidadId===id&&['recibido','leyendo','revisar'].includes(d.estado));const vals=state.docs.filter(d=>d.entidadId===id&&d.estado==='validado'&&es3T(d.fecha));const rec=vals.filter(d=>d.tipo==='recibida'),emi=vals.filter(d=>d.tipo==='emitida');const sum=(a,k)=>a.reduce((x,d)=>x+(+d[k]||0),0);return{pendientes,baseS:sum(rec,'base'),cuotaS:sum(rec,'cuota'),baseR:sum(emi,'base'),cuotaR:sum(emi,'cuota')};}
function render303(){if(!$('entidad303'))return;const id=$('entidad303').value;const r=resumen303(id);const res=r.cuotaR-r.cuotaS;$('kpi').innerHTML='<div><b>'+money(r.cuotaR)+'</b><span>IVA repercutido</span></div><div><b>'+money(r.cuotaS)+'</b><span>IVA soportado</span></div><div><b>'+money(res)+'</b><span>'+(res>=0?'A ingresar':'A compensar')+'</span></div>';$('tabla303').innerHTML='<tr><th>Concepto</th><th class="right">Importe</th></tr><tr><td>Base emitidas</td><td class="right">'+money(r.baseR)+'</td></tr><tr><td>Cuota repercutida</td><td class="right">'+money(r.cuotaR)+'</td></tr><tr><td>Base recibidas</td><td class="right">'+money(r.baseS)+'</td></tr><tr><td>Cuota soportada</td><td class="right">'+money(r.cuotaS)+'</td></tr><tr><td><b>Resultado 3T</b></td><td class="right"><b>'+money(res)+'</b></td></tr>';const box=$('bloque303');if(r.pendientes.length){box.className='warnbox';box.textContent='Hay '+r.pendientes.length+' documento(s) sin validar.';box.classList.remove('hidden');$('cerrarBtn').disabled=true;}else{box.className='okbox';box.textContent='Puedes autorizar si el importe es correcto.';box.classList.remove('hidden');$('cerrarBtn').disabled=false;}const pago=state.pagos[id+'-2026-3T'];$('pagoMsg').textContent=pago?'Autorizado. NRC: '+(pago.nrc||'no indicado')+'. '+money(pago.importe):'';if(pago)$('pagoMsg').className='okbox';}
function fillForm(d){editId=d?d.id:null;$('entidad').value=d&&d.entidadId||state.entidades[0]&&state.entidades[0].id||'';$('tipo').value=d&&d.tipo||'recibida';$('nif').value=d&&d.nif||'';$('nombre').value=d&&d.nombre||'';$('numero').value=d&&d.numero||'';$('fecha').value=d&&d.fecha||'';$('base').value=d&&d.base||'';$('ivaTipo').value=d&&d.ivaTipo||'21';$('cuota').value=d&&d.cuota||'';$('total').value=d&&d.total||'';archivoActual=d&&d.archivo||null;archivoNombre=d&&d.archivoNombre||'';preview();}
function preview(){const box=$('preview');if(!archivoActual){box.innerHTML='';return;}box.innerHTML=archivoActual.indexOf('data:application/pdf')===0?'<embed src="'+archivoActual+'" type="application/pdf" height="220">':'<img src="'+archivoActual+'" alt="Documento">';}
function recalc(){const base=Number($('base').value),tipo=Number($('ivaTipo').value);if(!Number.isNaN(base)&&$('base').value!==''){const cuota=Math.round(base*tipo)/100;if(!$('cuota').matches(':focus'))$('cuota').value=cuota.toFixed(2);if(!$('total').matches(':focus'))$('total').value=(base+Number($('cuota').value||cuota)).toFixed(2);}}
function leerCamposDeTexto(text){const t=text.replace(/\s+/g,' ');const nif=t.match(/\b([0-9]{8}[A-Z]|[A-Z][0-9]{7}[A-Z0-9])\b/i);const fecha=t.match(/\b(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})\b/);const total=t.match(/total[^0-9]{0,12}(\d+[.,]\d{2})/i);const base=t.match(/base[^0-9]{0,16}(\d+[.,]\d{2})/i);if(nif&&!$('nif').value)$('nif').value=nif[1].toUpperCase();if(fecha&&!$('fecha').value){var y=fecha[3].length===2?'20'+fecha[3]:fecha[3];$('fecha').value=y+'-'+fecha[2].padStart(2,'0')+'-'+fecha[1].padStart(2,'0');}if(base&&!$('base').value)$('base').value=base[1].replace(',','.');if(total&&!$('total').value)$('total').value=total[1].replace(',','.');recalc();}
async function ocr(){if(!archivoActual){$('ocrMsg').textContent='Primero elige un archivo.';return;}$('ocrMsg').textContent='Leyendo...';try{if(archivoActual.indexOf('data:application/pdf')===0&&window.pdfjsLib){const b64=archivoActual.split(',')[1];const bytes=Uint8Array.from(atob(b64),function(c){return c.charCodeAt(0);});const pdf=await pdfjsLib.getDocument({data:bytes}).promise;let text='';for(let i=1;i<=Math.min(pdf.numPages,3);i++){const page=await pdf.getPage(i);const content=await page.getTextContent();text+=content.items.map(function(it){return it.str;}).join(' ')+' ';}leerCamposDeTexto(text);}else if(window.Tesseract){leerCamposDeTexto((await Tesseract.recognize(archivoActual,'spa+eng')).data.text);}else{$('ocrMsg').textContent='Completa los datos a mano.';return;}$('ocrMsg').textContent='Lectura hecha. Revisa los campos.';}catch(e){$('ocrMsg').textContent='No se pudo leer bien. Completalo a mano.';}}
function guardar(){const doc={id:editId||nid(),entidadId:$('entidad').value,tipo:$('tipo').value,nif:$('nif').value.trim().toUpperCase(),nombre:$('nombre').value.trim(),numero:$('numero').value.trim(),fecha:$('fecha').value,base:$('base').value,ivaTipo:$('ivaTipo').value,cuota:$('cuota').value,total:$('total').value,archivo:archivoActual,archivoNombre:archivoNombre,estado:'revisar'};if(duplicado(doc,doc.id))doc.estado='duplicado';const i=state.docs.findIndex(function(d){return d.id===doc.id;});if(i>=0)state.docs[i]=Object.assign({},state.docs[i],doc);else state.docs.push(doc);save(state);editId=doc.id;renderLista();render303();$('ocrMsg').textContent=doc.estado==='duplicado'?'Guardado como duplicado.':'Guardado. Validalo si esta bien.';}
function setEstado(id,estado){const d=state.docs.find(function(x){return x.id===id;});if(!d)return;if(estado==='validado'){if(duplicado(d,id))d.estado='duplicado';else if(!cuadran(d)||!d.fecha||!d.total){d.estado='revisar';alert('No se puede validar: falta fecha/total o no cuadra.');}else d.estado='validado';}else d.estado=estado;save(state);renderLista();render303();}
$('pickBtn').onclick=function(){$('file').click();};$('file').onchange=function(e){leerFile(e.target.files[0]);};
function leerFile(file){if(!file)return;if(file.size>6000000){alert('Maximo 6 MB.');return;}const r=new FileReader();r.onload=function(){archivoActual=r.result;archivoNombre=file.name;preview();};r.readAsDataURL(file);}
$('base').addEventListener('input',recalc);$('ivaTipo').addEventListener('change',recalc);$('ocrBtn').onclick=ocr;$('saveBtn').onclick=guardar;
$('addEnt').onclick=function(){const nif=$('enNif').value.trim().toUpperCase(),nombre=$('enNom').value.trim();if(!nombre)return;state.entidades.push({id:nid(),nif:nif,nombre:nombre});$('enNif').value='';$('enNom').value='';save(state);renderEnt();};
$('listaEnt').addEventListener('click',function(e){const id=e.target.dataset.delEnt;if(!id||state.entidades.length<2)return;state.entidades=state.entidades.filter(function(x){return x.id!==id;});save(state);renderEnt();});
$('lista').addEventListener('click',function(e){if(e.target.dataset.edit){fillForm(state.docs.find(function(d){return d.id===e.target.dataset.edit;}));window.scrollTo({top:0,behavior:'smooth'});}if(e.target.dataset.val)setEstado(e.target.dataset.val,'validado');if(e.target.dataset.rej)setEstado(e.target.dataset.rej,'rechazado');});
$('entidad303').addEventListener('change',render303);
$('cerrarBtn').onclick=function(){const id=$('entidad303').value;const r=resumen303(id);if(r.pendientes.length)return;if(!$('autorizo').checked){alert('Marca la autorizacion.');return;}const nrc=$('nrc').value.trim().toUpperCase();if(nrc&&nrc.length!==22){alert('El NRC tiene 22 caracteres.');return;}state.pagos[id+'-2026-3T']={cuando:new Date().toISOString(),nrc:nrc,importe:r.cuotaR-r.cuotaS,autorizado:true};save(state);render303();};
document.querySelectorAll('.tabs button').forEach(function(b){b.onclick=function(){document.querySelectorAll('.tabs button').forEach(function(x){x.classList.remove('on');});b.classList.add('on');['docs','trimestre','entidades'].forEach(function(t){$('tab-'+t).classList.toggle('hidden',b.dataset.tab!==t);});if(b.dataset.tab==='trimestre')render303();};});
clock();renderEnt();renderLista();render303();
