const KEY='gestoria-v1';const CFG='gestoria-ocr-keys';const now=new Date();
const $=id=>document.getElementById(id);
const money=n=>(Number(n)||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
const nid=()=>crypto.randomUUID();
function load(){const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):{entidades:[{id:'e1',nif:'',nombre:'Mi actividad'}],docs:[],pagos:{}};}
function save(s){const c=structuredClone(s);c.docs.forEach(d=>{if(d.archivo&&d.archivo.length>700000)d.archivo=null;});localStorage.setItem(KEY,JSON.stringify(c));}
function keys(){try{return JSON.parse(localStorage.getItem(CFG)||'{}');}catch(e){return {};}}
function saveKeys(){localStorage.setItem(CFG,JSON.stringify({mindee:$('keyMindee').value.trim(),space:$('keySpace').value.trim()}));$('keyMsg').textContent='Claves guardadas en este dispositivo.';}
let state=load(),archivoActual=null,archivoBlob=null,archivoNombre='',editId=null;
if(window.pdfjsLib){pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';}
function es3T(f){if(!f)return false;const[y,m]=f.split('-').map(Number);return y===2026&&m>=7&&m<=9;}
function clock(){const d=new Date('2026-10-15T23:59:59'),p=new Date('2026-10-20T23:59:59');const via=now<=d?'Aun cabe domiciliar (hasta el 15 de octubre).':now<=p?'Ya no cabe domiciliar. Paga y guarda el NRC.':'Fuera de plazo voluntario del 3T.';$('clock').innerHTML='<b>3T 2026 · IVA</b><p>Domiciliacion: 15 oct · Presentacion: 20 oct.<br>'+via+'</p>';if($('viaPago'))$('viaPago').textContent=via;}
function fillEnt(sel){if(!sel)return;sel.innerHTML=state.entidades.map(e=>'<option value="'+e.id+'">'+(e.nombre||'Sin nombre')+(e.nif?' · '+e.nif:'')+'</option>').join('');}
function renderEnt(){fillEnt($('entidad'));fillEnt($('entidad303'));$('listaEnt').innerHTML=state.entidades.map(e=>'<div class="item"><div><b>'+e.nombre+'</b><br><small>'+(e.nif||'Sin NIF')+'</small></div><button class="btn ghost" data-del-ent="'+e.id+'">Quitar</button></div>').join('');}
function cuadran(d){const b=+d.base||0,c=+d.cuota||0,t=+d.total||0;if(!t&&!b)return false;return Math.abs(b+c-t)<0.05;}
function duplicado(doc,ignoreId){if(!doc.nif||!doc.numero)return false;return state.docs.some(d=>d.id!==ignoreId&&d.estado!=='rechazado'&&d.nif.replace(/\s/g,'').toUpperCase()===doc.nif.replace(/\s/g,'').toUpperCase()&&d.numero.trim().toUpperCase()===doc.numero.trim().toUpperCase());}
function renderLista(){const orden=[...state.docs].sort((a,b)=>(b.fecha||'').localeCompare(a.fecha||''));$('lista').innerHTML=orden.map(d=>{const ent=state.entidades.find(e=>e.id===d.entidadId);return '<div class="item"><div><span class="st '+d.estado+'">'+d.estado+'</span><b> '+(d.nombre||d.nif||'Sin nombre')+'</b><br><small>'+(ent?ent.nombre:'')+' · '+d.tipo+' · '+(d.fecha||'')+' · '+money(d.total)+'</small></div><div><button class="btn ghost" data-edit="'+d.id+'">Abrir</button>'+(d.estado!=='validado'?'<button class="btn ok" data-val="'+d.id+'">Validar</button>':'')+'</div></div>';}).join('')||'<p class="muted">Aun no hay documentos.</p>';}
function resumen303(id){const pendientes=state.docs.filter(d=>d.entidadId===id&&['recibido','leyendo','revisar'].includes(d.estado));const vals=state.docs.filter(d=>d.entidadId===id&&d.estado==='validado'&&es3T(d.fecha));const rec=vals.filter(d=>d.tipo==='recibida'),emi=vals.filter(d=>d.tipo==='emitida');const sum=(a,k)=>a.reduce((x,d)=>x+(+d[k]||0),0);return{pendientes,baseS:sum(rec,'base'),cuotaS:sum(rec,'cuota'),baseR:sum(emi,'base'),cuotaR:sum(emi,'cuota')};}
function render303(){if(!$('entidad303'))return;const id=$('entidad303').value;const r=resumen303(id);const res=r.cuotaR-r.cuotaS;$('kpi').innerHTML='<div><b>'+money(r.cuotaR)+'</b><span>IVA repercutido</span></div><div><b>'+money(r.cuotaS)+'</b><span>IVA soportado</span></div><div><b>'+money(res)+'</b><span>'+(res>=0?'A ingresar':'A compensar')+'</span></div>';$('tabla303').innerHTML='<tr><th>Concepto</th><th class="right">Importe</th></tr><tr><td>Cuota repercutida</td><td class="right">'+money(r.cuotaR)+'</td></tr><tr><td>Cuota soportada</td><td class="right">'+money(r.cuotaS)+'</td></tr><tr><td><b>Resultado 3T</b></td><td class="right"><b>'+money(res)+'</b></td></tr>';const box=$('bloque303');if(r.pendientes.length){box.className='warnbox';box.textContent='Hay '+r.pendientes.length+' documento(s) sin validar.';box.classList.remove('hidden');$('cerrarBtn').disabled=true;}else{box.className='okbox';box.textContent='Puedes autorizar si el importe es correcto.';box.classList.remove('hidden');$('cerrarBtn').disabled=false;}const pago=state.pagos[id+'-2026-3T'];$('pagoMsg').textContent=pago?'Autorizado. NRC: '+(pago.nrc||'no indicado'):'';}
function fillForm(d){editId=d?d.id:null;$('entidad').value=d&&d.entidadId||state.entidades[0]&&state.entidades[0].id||'';$('tipo').value=d&&d.tipo||'recibida';$('nif').value=d&&d.nif||'';$('nombre').value=d&&d.nombre||'';$('numero').value=d&&d.numero||'';$('fecha').value=d&&d.fecha||'';$('base').value=d&&d.base||'';$('ivaTipo').value=d&&d.ivaTipo||'21';$('cuota').value=d&&d.cuota||'';$('total').value=d&&d.total||'';archivoActual=d&&d.archivo||null;preview();}
function preview(){const box=$('preview');if(!archivoActual){box.innerHTML='';return;}box.innerHTML=archivoActual.indexOf('pdf')>0?'<embed src="'+archivoActual+'" type="application/pdf" height="200">':'<img src="'+archivoActual+'" alt="doc">';}
function recalc(){const base=Number($('base').value),tipo=Number($('ivaTipo').value);if(!Number.isNaN(base)&&$('base').value!==''){const cuota=Math.round(base*tipo)/100;if(!$('cuota').matches(':focus'))$('cuota').value=cuota.toFixed(2);if(!$('total').matches(':focus'))$('total').value=(base+Number($('cuota').value||cuota)).toFixed(2);}}
function ymd(s){if(!s)return '';const d=String(s).slice(0,10);if(/^\d{4}-/.test(d))return d;const m=d.match(/(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})/);if(!m)return '';const y=m[3].length===2?'20'+m[3]:m[3];return y+'-'+m[2].padStart(2,'0')+'-'+m[1].padStart(2,'0');}
function applyMindee(doc){const p=(doc.inference&&doc.inference.prediction)||{};const v=k=>p[k]&&p[k].value!=null?p[k].value:'';if(v('supplier_company_registration))$('nif').value=String(v('supplier_company_registration')).toUpperCase();
  if(v('supplier_name))$('nombre').value=v('supplier_name');
  if(v('invoice_number))$('numero').value=v('invoice_number');
  if(v('invoice_date))$('fecha').value=ymd(v('invoice_date'));
  if(v('total_net))$('base').value=Number(v('total_net')).toFixed(2);
  if(v('total_tax))$('cuota').value=Number(v('total_tax')).toFixed(2);
  if(v('total_amount))$('total').value=Number(v('total_amount')).toFixed(2);
  const taxes=p.taxes||[];if(taxes[0]&&taxes[0].rate!=null)$('ivaTipo').value=String(Math.round(taxes[0].rate));
  $('ocrRaw').value=JSON.stringify(p,null,2);
}
function leerCamposDeTexto(text){$('ocrRaw').value=text||'';const t=(text||'').replace(/\s+/g,' ');const nif=t.match(/\b([0-9]{8}[A-Z]|[XYZ][0-9]{7}[A-Z]|[ABCDEFGHJNPQRSUVW][0-9]{7}[0-9A-J])\b/i);const fecha=t.match(/\b(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})\b/);const tot=t.match(/(?:total|importe)[^0-9]{0,14}(\d+[.,]\d{2})/i);const base=t.match(/base[^0-9]{0,16}(\d+[.,]\d{2})/i);if(nif)$('nif').value=nif[1].toUpperCase();if(fecha)$('fecha').value=ymd(fecha[1]+'/'+fecha[2]+'/'+fecha[3]);if(base)$('base').value=base[1].replace(',','.');if(tot)$('total').value=tot[1].replace(',','.');recalc();}
async function mindeeRead(blob,token){const fd=new FormData();fd.append('document',blob,archivoNombre||'factura.pdf');const r=await fetch('https://api.mindee.net/v1/products/mindee/invoices/v4/predict',{method:'POST',headers:{Authorization:'Token '+token},body:fd});const j=await r.json();if(!r.ok)throw new Error((j.api_request&&j.api_request.error&&j.api_request.error.message)||('Mindee '+r.status));return j.document;}
async function spaceRead(blob,token){const fd=new FormData();fd.append('file',blob,archivoNombre||'doc.jpg');fd.append('apikey',token);fd.append('language','spa');fd.append('isOverlayRequired','false');fd.append('OCREngine','2');const r=await fetch('https://api.ocr.space/parse/image',{method:'POST',body:fd});const j=await r.json();if(j.IsErroredOnProcessing)throw new Error(j.ErrorMessage||'OCR.space');return ((j.ParsedResults||[])[0]||{}).ParsedText||'';}
async function ocr(){if(!archivoBlob&&!archivoActual){$('ocrMsg').textContent='Primero elige un archivo.';return;}const k=keys();$('ocrMsg').textContent='Leyendo...';try{if(k.mindee&&archivoBlob){try{const doc=await mindeeRead(archivoBlob,k.mindee);applyMindee(doc);$('ocrMsg').textContent='Leído con Mindee. Revisa y valida.';return;}catch(e){$('ocrMsg').textContent='Mindee: '+e.message+'. Pruebo reserva...';}}
  if(k.space&&archivoBlob){const text=await spaceRead(archivoBlob,k.space);leerCamposDeTexto(text);$('ocrMsg').textContent='Leído con OCR.space. Revisa campos.';return;}
  if(!k.mindee&&!k.space){$('ocrMsg').textContent='Pon una clave en la pestaña Lector. Sin eso esto no lee facturas como Holded.';return;}
  $('ocrMsg').textContent='No pude llamar al lector. Revisa la clave o el formato (JPEG/PNG/PDF).';
}catch(e){$('ocrMsg').textContent='Fallo: '+e.message;}}
function guardar(){const doc={id:editId||nid(),entidadId:$('entidad').value,tipo:$('tipo').value,nif:$('nif').value.trim().toUpperCase(),nombre:$('nombre').value.trim(),numero:$('numero').value.trim(),fecha:$('fecha').value,base:$('base').value,ivaTipo:$('ivaTipo').value,cuota:$('cuota').value,total:$('total').value,archivo:archivoActual,archivoNombre:archivoNombre,estado:'revisar'};if(duplicado(doc,doc.id))doc.estado='duplicado';const i=state.docs.findIndex(d=>d.id===doc.id);if(i>=0)state.docs[i]=Object.assign({},state.docs[i],doc);else state.docs.push(doc);save(state);editId=doc.id;renderLista();$('ocrMsg').textContent=doc.estado==='duplicado'?'Duplicado.':'Guardado. Valida si esta bien.';}
function setEstado(id,estado){const d=state.docs.find(x=>x.id===id);if(!d)return;if(estado==='validado'){if(!cuadran(d)||!d.fecha||!d.total){alert('No se puede validar: falta fecha/total o no cuadra.');return;}d.estado='validado';}else d.estado=estado;save(state);renderLista();render303();}
function leerFile(file){if(!file)return;archivoNombre=file.name;archivoBlob=file;if(file.size>8000000){alert('Maximo 8 MB');return;}const r=new FileReader();r.onload=function(){archivoActual=r.result;preview();ocr();};r.readAsDataURL(file);}
$('pickBtn').onclick=function(){$('file').click();};
$('file').onchange=function(e){leerFile(e.target.files[0]);};
$('drop').addEventListener('dragover',e=>e.preventDefault());
$('drop').addEventListener('drop',e=>{e.preventDefault();leerFile(e.dataTransfer.files[0]);});
$('base').addEventListener('input',recalc);$('ivaTipo').addEventListener('change',recalc);
$('ocrBtn').onclick=ocr;$('saveBtn').onclick=guardar;$('saveKeys').onclick=saveKeys;
$('addEnt').onclick=function(){const nombre=$('enNom').value.trim();if(!nombre)return;state.entidades.push({id:nid(),nif:$('enNif').value.trim().toUpperCase(),nombre:nombre});$('enNif').value='';$('enNom').value='';save(state);renderEnt();};
$('lista').addEventListener('click',function(e){if(e.target.dataset.edit){fillForm(state.docs.find(d=>d.id===e.target.dataset.edit));}if(e.target.dataset.val)setEstado(e.target.dataset.val,'validado');});
$('entidad303').addEventListener('change',render303);
$('cerrarBtn').onclick=function(){const id=$('entidad303').value;const r=resumen303(id);if(r.pendientes.length)return;if(!$('autorizo').checked){alert('Marca la autorizacion.');return;}const nrc=$('nrc').value.trim().toUpperCase();if(nrc&&nrc.length!==22){alert('NRC: 22 caracteres.');return;}state.pagos[id+'-2026-3T']={cuando:new Date().toISOString(),nrc:nrc,importe:r.cuotaR-r.cuotaS,autorizado:true};save(state);render303();};
document.querySelectorAll('.tabs button').forEach(function(b){b.onclick=function(){document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');['docs','trimestre','entidades','config'].forEach(t=>$('tab-'+t).classList.toggle('hidden',b.dataset.tab!==t));if(b.dataset.tab==='trimestre')render303();if(b.dataset.tab==='config'){const k=keys();$('keyMindee').value=k.mindee||'';$('keySpace').value=k.space||'';}};});
clock();renderEnt();renderLista();render303();
